### ISSUE TITLE
License of the logo

### ISSUE THREAD

**Issue by andir** [kirelagin/nixos-init#2]
Just found out about the project and I really like the logo. Do you mind adding a LICENSE file to the repo? I am mainly thinking about ordering a few T-Shirts/Hoodies with that logo :-)

**Comment by kirelagin** [comment]
Huh, to be honest, I didn’t expect anyone to need the logo of a project that is still nowhere close to actually doing anything useful :).

I was planning to do all the repository chores, including adding licensing information, when the code in the repo somewhat works... also, IIRC, I took the systemd logo from Wikipedia (so, I am currently violating its license, CC-BY), and I took the Nix logo from nixos-artwork (which doesn’t have any license at all), so I would strongly recommend you not use this logo anywhere until I sort everything and start to comply with the original licenses.

However, if you really want to use the logo ASAP, you can help me by figuring out under which license nixos-artwork is supposed to be distributed and then how to license my logo, which is derived from both.

**Comment by kirelagin** [comment]
Oh, ok, found it, the NixOS logo is actually CC-BY as well, so that’s easy.

**Comment by kirelagin** [comment]
Aha, the one in Wikipedia is actually CC-BY-SA, so, I guess, I have to go with it as the least common multiple.

**Comment by andir** [comment]
Thank you!
To be clear I only was after the logo because of the systemd + NixOS combination. This project is still a great idea and I am eager to see where it goes. :)
